version: "3"

services:
  db:
    image: mysql:5.7
    container_name: docker-local-mysql
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db_postgres:
    container_name: docker-local-postgres
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=duwonyi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5555:80
    volumes:
      - "./pgadmin-data:/var/lib/pgadmin"
